title: Drew C Youngren
# description: 
show_downloads: false
# google_analytics:
theme: jekyll-theme-slate
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  teaching:
    output: true
    permalink: /:collection/:name

